name: pr-auto-assign
on: [pull_request]

jobs:
  pr-auto-assign:
    name: pr-auto-assign
    runs-on: ubuntu-latest
    steps:
      - name: execute
        uses: ManabuSeki/pr-auto-assign-action@v0.0.2
        with:
          github_token: ${{ secrets.github_token }}
          config_path: .github/auto_assign.yml

